module.exports = {
  content: ["./src/**/*.{html,js,vue}"],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'dark': '#2A2438',
      'midnight': '#3E065F',
      'darkpurple': '#700B97',
      'purple': '#8E05C2',
      'white': '#ffffff',
      'metal': '#565584',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
      'blue': '#1fb6ff',
      'pink': '#ff49db',
      'orange': '#ff7849',
      'green': '#13ce66',
      'yellow': '#ffc82c',
      'darkgray': '#273444',
      'gray': '#8492a6',
      'gray-light': '#d3dce6',
    },
    extend: {},
  },
  plugins: [],
}